### ISSUE TITLE
[Meta] Improve support for Kafka 2.x

### ISSUE THREAD

**Issue by robbavey** [logstash-plugins/logstash-integration-kafka#22]
This meta issue will contain links to other issues discovered to improve support for Kafka `2.x`. 

 - [x] Bump Kafka clients to 2.4 #14
 - [x] Avoid use of deprecated `poll(long)` method #21
 - [x] Update docs to better reflect behaviour and recommendations for Kafka 2.0 #20

**Comment by mbarretta** [comment]
linking https://github.com/logstash-plugins/logstash-integration-kafka/issues/82, which includes the ask to use Static Membership from v2.3

**Comment by andsel** [comment]
Given that the list is checked I think we could close this. cc @roaksoax @robbavey
