### ISSUE TITLE
[Meta] use avro serdes library and Schema Registry to decode avro messages

### ISSUE THREAD

**Issue by andsel** [logstash-plugins/logstash-integration-kafka#58]
### Overview

Kafka Avro SerDes let the users of this plugin to centrally manage the schemas of Avro messages by mean of  [Confluent's Schema Registry](https://docs.confluent.io/current/schema-registry/). This force the plugin to interface with schema registry to retrieve the schema in decoding phase (input plugin) and eventually in the encoding if we decide to adapt also the output plugin.

Related to:
- original feature request #11 
- previous tempted work: request issue https://github.com/logstash-plugins/logstash-input-kafka/issues/238 and PR https://github.com/logstash-plugins/logstash-input-kafka/pull/239

### Description

The user should upload the Avro schema he desire to use for deserialization of messages from a topic in a specific [subject](https://docs.confluent.io/current/schema-registry/index.html#schemas-subjects-and-topics). The subject must follow a naming convention, `<topic name>-value`. He could decide to upload the schema through the Confluent's Control Center UI or using the [ReST API ](https://docs.confluent.io/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)-versions). To be able to connect he has to set credentials for the Schema Registry (API_KEY, API_SECRET) and the URL where it's exposed. The plugin retrieve the schema and start deserializing the data. The deserialization happens at Kafka input layer, without defining the Avro codec.

### Usage example
```
input {
  kafka {
    schema_registry_url => "http://myschema.foo.com"
    schema_registry_api_key => "key from Schema Registry cloud"
    schema_registry_api_secret => "secret from Schema Registry cloud"
    schema_registry_proxy_host => "proxy host to use"
    schema_registry_proxy_port => 1234
  }
}

```

### Security
Schema Registry could be secured using https and basic authentication to protect. Looking and an [example](https://docs.confluent.io/current/schema-registry/schema_registry_ccloud_tutorial.html#environment-setup) and [client configuration guide](https://docs.confluent.io/current/security/security_tutorial.html#configure-clients) most of the settings (like `ssl.truststore.location` or  `sasl.jaas.config`) are already defined in existing Kafka plugins, so this part of the specification requires only to eventually provide `api key` and `api secret` for basic authentication or a `bearer token`. The properties for SSL part are already present in the plugin’s options. To use TLS during the communication with Schema Registry service, just put `https` in front of the hostname/IP.

### Possible configuration clashes
Kafka input and output already provides some configuration that could conflict with the Kafka Avro Serdes configuration. The Kafka avro serdes is the encoding library that nest into the Kafka client to use the Schema Registry to retrieve Avro schemas, this impose the use of a specific deserializer class (`io.confluent.kafka.serializers.KafkaAvroDeserializer`) so this conflict with existing [value_deserializer_class](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html#plugins-inputs-kafka-value_deserializer_class).
The checks that are done at plugins registration time, and in case of failure abort the pipeline creations are:
- if use `schema_registry_url` then prohibit the definition of `value_deserializer_class` (`value_serializer_class` for output plugin)
- verify the schema registry specified by `schema_registry_url` is reachable considering all the security settings (key and secret and TLS)
- verify that a schema subject exists under naming convention `<topic name>-value` for all `topics` defined
- verify that `topics_pattern` is undefined when using the schema registry.

### Design decisions

To implement this deserialization/serialization there are two possible paths:
- use the `logstash-codec-avro` to behave as a configuration carrier
- use the `logstash-input-kafka` / `logstash-output-kafka`

Choosing the first could land to some inconsistencies, having a codec that only carries configuration and that doesn't executes any decoding login under some configuration is not a good citizen of the plugins ecosystems. The chosen option is to implement the codec logic inside input/output plugin, that already decoded directly some data ([value_deserializer_class](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html#plugins-inputs-kafka-value_deserializer_class))

----

### Implementation plan:

- [x] change the `kafka_test_setup.sh` to start also [Confluent's Schema registry](https://docs.confluent.io/current/schema-registry/installation/config.html)
- [x] write the definition of a schema and push on the registry
- [x] include the [Kafka-streams-avro-serdes](https://mvnrepository.com/artifact/io.confluent/kafka-streams-avro-serde?repo=confluent-packages) dependency
- [x] create a test to use the uploaded schema to write and read data using it
- [x] implement the part, and write a test that checks the exception raised if configuration settings are correct
- [x] update the documentation
- [x] add management of `key` and `secret` used to secure connection in case the Schema Registry is from Confluent's cloud

**Comment by fbaligand** [comment]
I'm very interessed by this feature!
In our company, our roadmap is to use only Avro Schema Registry for all Kafka topics.
And we have multiple cases where an integration between a Logstash and a Kafka Topic are planned!

**Comment by andsel** [comment]
Closed by #51

**Comment by roaksoax** [comment]
@andsel your example lists:

    schema_registry_proxy_host => "proxy host to use"
    schema_registry_proxy_port => 1234

However, the official docs *only* have:

  schema_registry_proxy

**Comment by andsel** [comment]
My bad, the Kafka input brings `schema_registry_proxy` which contains an url, so like `http://proxy_host:proxy_port` and with https://github.com/logstash-plugins/logstash-integration-kafka/blob/c0b6befad9492bd80cc419eb1582d715fb5f2189/lib/logstash/plugin_mixins/common.rb#L69-L81 it splits in host and port, so my example is outdated
